export const PATHS = {
    index:'/',
    login:'/login',
    signup:'/signup',
    admin:'/admin',
    customer:'/customer',
    kitchen:'/kitchen',
    profile:'/profile',
    analytics:'/analytics',
    order:'/order',
    review:'/review',
    shops:'/shops',
    shopDetail:'/items/:shopId',
    cart:'/cart',
    history:'/order-history',
    category:'/category',
    items:'/items',
    orderAdmin:'/admin/order',
    report: '/report'
}